title: Software KST FDü
description: Installationsanleitungen für Schülerinnen der Kantonsschule Dübendorf (KST FDü)

remote_theme: just-the-docs/just-the-docs

url: "https://cyrilblum.github.io"
baseurl: "/KSTfDu"

search_enabled: true
heading_anchors: true

footer_content: "Kantonsschule KSTfDü, © Cyril Blum"

nav_sort: order

plugins:
  - jekyll-remote-theme
  - jekyll-seo-tag
